# Generated by Django 3.2.8 on 2021-10-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlucoseReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reading_datetime', models.DateTimeField()),
                ('meid', models.CharField(db_index=True, max_length=255)),
                ('blood_glucose', models.PositiveIntegerField()),
                ('measurement_type', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BloodPressureReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reading_datetime', models.DateTimeField()),
                ('meid', models.CharField(db_index=True, max_length=255)),
                ('systolic_measurement', models.PositiveIntegerField()),
                ('diastolic_measurement', models.PositiveIntegerField()),
                ('pulse', models.PositiveIntegerField()),
                ('mean_pressure', models.PositiveIntegerField(null=True)),
                ('average_measurement', models.PositiveIntegerField(null=True)),
                ('ihb_index', models.PositiveIntegerField(null=True)),
                ('stiffness_index', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
