# Generated by Django 3.2.8 on 2021-10-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial_squashed_0003_auto_20211019_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(db_index=True)),
                ('processing_succeeded', models.BooleanField()),
            ],
        ),
    ]
