# Generated by Django 3.2.8 on 2021-10-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211021_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='decrypted_content',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
