# Generated by Django 3.2.8 on 2021-10-21 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_logentry_decrypted_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='encryption_succeeded',
            new_name='decryption_succeeded',
        ),
    ]
